---
title: "Merge_datasets"
author: "Milou Sep"
date: "4/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
rm(list = ls()) #clean environment
# load files from OSF
library(osfr)
# Authenticate to OSF (see: http://centerforopenscience.github.io/osfr/articles/auth.html). Via osf_auth("PAT") in the commentline. (note PAT can be derived from OSF)

library(readxl)
library(dplyr)
```

# retrieve OSF files 
```{r }
osf_retrieve_file("tqmwb") %>% osf_download(path = "data", conflicts="overwrite") # search 1
osf_retrieve_file("xqpm3") %>% osf_download(path = "data", conflicts="overwrite") # search 2
osf_retrieve_file("wbrcm") %>% osf_download(path = "data", conflicts="overwrite") # search 3
```

# load data
```{r}
s1 <- read_excel("data/TRACE data_collection_search1.xlsx", na = c(" ", "-"))#s1
s2a <- read_excel("data/TRACE data_collection_search2.xlsx", sheet = "animal_inclusions_s2", na = c(" ", "-"))#s2
s2h <- read_excel("data/TRACE data_collection_search2.xlsx", sheet = "human_inclusions_s2", na = c(" ", "-"))#s2
s3a <- read_excel("data/TRACE_data_collection_search3.xlsx", sheet = "animal.inclusions.s3", na = c(" ", "-"))#s3
s3h <- read_excel("data/TRACE_data_collection_search3.xlsx", sheet = "human.inclusions.s3", na = c(" ", "-"))#s3
```

# select and rename S1
```{r}
str(s1)

df1 <- select(s1,  `Reference_First Author` , `Reference_Publication Year` , `Reference_PMID` , `inclusion` , `subject` ,  `Data_Subjects_n_ptsd` , `Data_Subjects_n_control` , `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , `Data_Subjects_gender_control (M = male; F = female; - = not reported)` , `Data_Subjects_m_Age_ptsd (- = not reported)` , `Data_Subjects_sd_Age_ptsd (- = not reported)` , `Data_Subjects_m_Age_control (- = not reported)` , `Data_Subjects_sd_Age_control (- = not reported)` , `Data_Subjects_FS_#Shocks` , `Data_Subjects_FS_Amperage(mA)` , `Data_Subjects_PTSDtypeSHORT2` , `Data_Subjects_Controltype` , `Data_Subjects_Strain_or_Population` , `Data_Subjects_ptsd-measure` , `Data_Method_TimeTask-Trauma` , `task` , `Data_Method_animal light dark testing?` , `measure` , `Comparison` , `ID_Experimental_group` , `ID_Control_group` , `Data_Outcome1_VarName` , `Data_Outcome1_M` , `Data_Outcome1_SD` , `Data_Outcome1_SEM` , `Data_Outcome2_VarName` , `Data_Outcome2_M` , `Data_Outcome2_SD` , `Data_Outcome2_SEM` )

# Rename
df1 %>% rename(
  author =  `Reference_First Author` , 
  year = `Reference_Publication Year` , 
  PMID = `Reference_PMID` , 
  decision = `inclusion` , 
  subject = `subject` , 
  nPTSD = `Data_Subjects_n_ptsd` , 
  nHC =`Data_Subjects_n_control` , 
  sex.PTSD = `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , 
  sex.HC =`Data_Subjects_gender_control (M = male; F = female; - = not reported)` ,
  age.PTSD.m =`Data_Subjects_m_Age_ptsd (- = not reported)` , 
  age.PTSD.sd =`Data_Subjects_sd_Age_ptsd (- = not reported)` , 
  age.HC.m =`Data_Subjects_m_Age_control (- = not reported)` ,
  age.HC.sd =`Data_Subjects_sd_Age_control (- = not reported)` ,
  shocks.num = `Data_Subjects_FS_#Shocks` , 
  shocks.amp =`Data_Subjects_FS_Amperage(mA)` , 
  ptsd.type = `Data_Subjects_PTSDtypeSHORT2` , 
  control.type = `Data_Subjects_Controltype` , 
  population = `Data_Subjects_Strain_or_Population` , 
  ptsd.measure = `Data_Subjects_ptsd-measure` , 
  time = `Data_Method_TimeTask-Trauma` , 
  task = `task` , 
  rhythm  =`Data_Method_animal light dark testing?` , 
  measure = `measure` , 
  comparison = `Comparison` , 
  idPTSD =`ID_Experimental_group` , 
  idHC = `ID_Control_group` , 
  outcomePTSD = `Data_Outcome1_VarName` , 
  meanPTSD = `Data_Outcome1_M` , 
  sdPTSD = `Data_Outcome1_SD` , 
  semPTSD = `Data_Outcome1_SEM` , 
  outcomeHC = `Data_Outcome2_VarName` , 
  meanHC =`Data_Outcome2_M` , 
  sdHC = `Data_Outcome2_SD` , 
  semHC = `Data_Outcome2_SEM` 
) -> df1.renamed

glimpse(df1.renamed)
```

# select and rename S2

## s2 animal
```{r}
str(s2a)

  
df2a <- select(s2a,
`Reference_First Author_SH` , `Reference_Publication Year_SH` , `Reference_PMID_SH` , `inclusion.final` , `subject` , `Data_Subjects_n_ptsd` , `Data_Subjects_n_control` , `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , `Data_Subjects_gender_control (M = male; F = female; - = not reported)` , `Data_Subjects_m_Age_ptsd (- = not reported)` , `Data_Subjects_sd_Age_ptsd (- = not reported)` , `Data_Subjects_m_Age_control (- = not reported)` , `Data_Subjects_sd_Age_control (- = not reported)` , `Data_Subjects_FS_#Shocks` , `Data_Subjects_FS_Amperage(mA)` , `Data_Subjects_PTSDtypeSHORT2` , `Data_Subjects_Controltype` , `Data_Subjects_Strain_or_Population` , `Data_Subjects_ptsd-measure` , `Data_Subjects_ResSus.split` , `Data_Method_TimeTask-Trauma` , `task` , `Data_Method_animal light dark testing?` , `measure` , `Comparison` , `ID_Experimental_group` , `ID_Control_group` , `Data_Outcome1_VarName` , `Data_Outcome1_M` , `Data_Outcome1_SD` , `Data_Outcome1_SEM` , `Data_Outcome2_VarName` , `Data_Outcome2_M` , `Data_Outcome2_SD` , `Data_Outcome2_SEM` )


df2a %>% rename(
  author =  `Reference_First Author_SH` , 
  year = `Reference_Publication Year_SH` , 
  PMID = `Reference_PMID_SH` , 
  decision = `inclusion.final` , 
  subject = `subject` , 
  nPTSD = `Data_Subjects_n_ptsd` , 
  nHC =`Data_Subjects_n_control` , 
  sex.PTSD = `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , 
  sex.HC =`Data_Subjects_gender_control (M = male; F = female; - = not reported)` ,
  age.PTSD.m =`Data_Subjects_m_Age_ptsd (- = not reported)` , 
  age.PTSD.sd =`Data_Subjects_sd_Age_ptsd (- = not reported)` , 
  age.HC.m =`Data_Subjects_m_Age_control (- = not reported)` ,
  age.HC.sd =`Data_Subjects_sd_Age_control (- = not reported)` ,
  shocks.num = `Data_Subjects_FS_#Shocks` , 
  shocks.amp =`Data_Subjects_FS_Amperage(mA)` , 
  ptsd.type = `Data_Subjects_PTSDtypeSHORT2` , 
  control.type = `Data_Subjects_Controltype` , 
  population = `Data_Subjects_Strain_or_Population` , 
  ptsd.measure = `Data_Subjects_ptsd-measure` , 
  
  # not in s1 or human
  res.sus.split = `Data_Subjects_ResSus.split`,
  
  time = `Data_Method_TimeTask-Trauma` , 
  task = `task` , 
  rhythm  =`Data_Method_animal light dark testing?` , 
  measure = `measure` , 
  comparison = `Comparison` , 
  idPTSD =`ID_Experimental_group` , 
  idHC = `ID_Control_group` , 
  outcomePTSD = `Data_Outcome1_VarName` , 
  meanPTSD = `Data_Outcome1_M` , 
  sdPTSD = `Data_Outcome1_SD` , 
  semPTSD = `Data_Outcome1_SEM` , 
  outcomeHC = `Data_Outcome2_VarName` , 
  meanHC =`Data_Outcome2_M` , 
  sdHC = `Data_Outcome2_SD` , 
  semHC = `Data_Outcome2_SEM` 
) -> df2a.renamed

glimpse(df2a.renamed)

# add missing colums


```

## human
```{r}
str(s2h)
  
df2h <- select(s2h,
`Reference_First Author_SH` , `Reference_Publication Year_SH` , `Reference_PMID_SH` , `inclusion.final` , `subject` , `Data_Subjects_n_ptsd` , `Data_Subjects_n_control` , `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , `Data_Subjects_gender_control (M = male; F = female; - = not reported)` , `Data_Subjects_m_Age_ptsd (- = not reported)` , `Data_Subjects_sd_Age_ptsd (- = not reported)` , `Data_Subjects_m_Age_control (- = not reported)` , `Data_Subjects_sd_Age_control (- = not reported)` , `Data_Subjects_FS_#Shocks` , `Data_Subjects_FS_Amperage(mA)` , `Data_Subjects_PTSDtypeSHORT2` , `Data_Subjects_Controltype` , `Data_Subjects_Strain_or_Population` , `Data_Subjects_ptsd-measure` , #`Data_Subjects_ResSus.split` , 
`Data_Method_TimeTask-Trauma` , `task` , `Data_Method_animal light dark testing?` , `measure` , `Comparison` , `ID_Experimental_group` , `ID_Control_group` , `Data_Outcome1_VarName` , `Data_Outcome1_M` , `Data_Outcome1_SD` , `Data_Outcome1_SEM` , `Data_Outcome2_VarName` , `Data_Outcome2_M` , `Data_Outcome2_SD` , `Data_Outcome2_SEM` )


df2h %>% rename(
  author =  `Reference_First Author_SH` , 
  year = `Reference_Publication Year_SH` , 
  PMID = `Reference_PMID_SH` , 
  decision = `inclusion.final` , 
  subject = `subject` , 
  nPTSD = `Data_Subjects_n_ptsd` , 
  nHC =`Data_Subjects_n_control` , 
  sex.PTSD = `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , 
  sex.HC =`Data_Subjects_gender_control (M = male; F = female; - = not reported)` ,
  age.PTSD.m =`Data_Subjects_m_Age_ptsd (- = not reported)` , 
  age.PTSD.sd =`Data_Subjects_sd_Age_ptsd (- = not reported)` , 
  age.HC.m =`Data_Subjects_m_Age_control (- = not reported)` ,
  age.HC.sd =`Data_Subjects_sd_Age_control (- = not reported)` ,
  shocks.num = `Data_Subjects_FS_#Shocks` , 
  shocks.amp =`Data_Subjects_FS_Amperage(mA)` , 
  ptsd.type = `Data_Subjects_PTSDtypeSHORT2` , 
  control.type = `Data_Subjects_Controltype` , 
  population = `Data_Subjects_Strain_or_Population` , 
  ptsd.measure = `Data_Subjects_ptsd-measure` , 
  
  # not in s1 or human
  # res.sus.split = `Data_Subjects_ResSus.split`,
  
  time = `Data_Method_TimeTask-Trauma` , 
  task = `task` , 
  rhythm  =`Data_Method_animal light dark testing?` , 
  measure = `measure` , 
  comparison = `Comparison` , 
  idPTSD =`ID_Experimental_group` , 
  idHC = `ID_Control_group` , 
  outcomePTSD = `Data_Outcome1_VarName` , 
  meanPTSD = `Data_Outcome1_M` , 
  sdPTSD = `Data_Outcome1_SD` , 
  semPTSD = `Data_Outcome1_SEM` , 
  outcomeHC = `Data_Outcome2_VarName` , 
  meanHC =`Data_Outcome2_M` , 
  sdHC = `Data_Outcome2_SD` , 
  semHC = `Data_Outcome2_SEM` 
) -> df2h.renamed

glimpse(df2h.renamed)
```


# S3

## animal
```{r}
str(s3a)

df3a <- select(s3a,
`First Author` , `Publication Year` , `PMID` , `inclusion.final` , `subject` , `Data_Subjects_n_ptsd` , `Data_Subjects_n_control` , `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , `Data_Subjects_gender_control (M = male; F = female; - = not reported)` , `Data_Subjects_m_Age_ptsd (- = not reported)` , `Data_Subjects_sd_Age_ptsd (- = not reported)` , `Data_Subjects_m_Age_control (- = not reported)` , `Data_Subjects_sd_Age_control (- = not reported)` , `Data_Subjects_FS_#Shocks` , `Data_Subjects_FS_Amperage(mA)` , `Data_Subjects_PTSDtypeSHORT2` , `Data_Subjects_Controltype` , `Data_Subjects_Strain_or_Population` , #`Data_Subjects_ptsd-measure` , 

`Data_Subjects_ResSus.split.final` , 

`Data_Method_TimeTask-Trauma` , `task` , `Data_Method_animal light dark testing?` , `measure` , `Comparison` , `ID_Experimental_group` , `ID_Control_group` , `Data_Outcome1_VarName` , `Data_Outcome1_M` , `Data_Outcome1_SD` , `Data_Outcome1_SEM` , `Data_Outcome2_VarName` , `Data_Outcome2_M` , `Data_Outcome2_SD` , `Data_Outcome2_SEM` )



df3a %>% rename(
  author =  `First Author` , 
  year = `Publication Year` , 
  PMID = `PMID` , 
  decision = `inclusion.final` , 
  subject = `subject` , 
  nPTSD = `Data_Subjects_n_ptsd` , 
  nHC =`Data_Subjects_n_control` , 
  sex.PTSD = `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , 
  sex.HC =`Data_Subjects_gender_control (M = male; F = female; - = not reported)` ,
  age.PTSD.m =`Data_Subjects_m_Age_ptsd (- = not reported)` , 
  age.PTSD.sd =`Data_Subjects_sd_Age_ptsd (- = not reported)` , 
  age.HC.m =`Data_Subjects_m_Age_control (- = not reported)` ,
  age.HC.sd =`Data_Subjects_sd_Age_control (- = not reported)` ,
  shocks.num = `Data_Subjects_FS_#Shocks` , 
  shocks.amp =`Data_Subjects_FS_Amperage(mA)` , 
  ptsd.type = `Data_Subjects_PTSDtypeSHORT2` , 
  control.type = `Data_Subjects_Controltype` , 
  population = `Data_Subjects_Strain_or_Population` , 
  
  # only in human s3
  # ptsd.measure = `Data_Subjects_ptsd-measure` , 
  
  # not in s1 or human s2
   res.sus.split = `Data_Subjects_ResSus.split.final`,
  
  time = `Data_Method_TimeTask-Trauma` , 
  task = `task` , 
  rhythm  =`Data_Method_animal light dark testing?` , 
  measure = `measure` , 
  comparison = `Comparison` , 
  idPTSD =`ID_Experimental_group` , 
  idHC = `ID_Control_group` , 
  outcomePTSD = `Data_Outcome1_VarName` , 
  meanPTSD = `Data_Outcome1_M` , 
  sdPTSD = `Data_Outcome1_SD` , 
  semPTSD = `Data_Outcome1_SEM` , 
  outcomeHC = `Data_Outcome2_VarName` , 
  meanHC =`Data_Outcome2_M` , 
  sdHC = `Data_Outcome2_SD` , 
  semHC = `Data_Outcome2_SEM` 
) -> df3a.renamed

```

## human

```{r}
df3h <- select(s3h,
`First Author` , `Publication Year` , `PMID` , `inclusion.final` , `subject` , `Data_Subjects_n_ptsd` , `Data_Subjects_n_control` , `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , `Data_Subjects_gender_control (M = male; F = female; - = not reported)` , `Data_Subjects_m_Age_ptsd (- = not reported)` , `Data_Subjects_sd_Age_ptsd (- = not reported)` , `Data_Subjects_m_Age_control (- = not reported)` , `Data_Subjects_sd_Age_control (- = not reported)` ,

#`Data_Subjects_FS_#Shocks` , `Data_Subjects_FS_Amperage(mA)` , 

`Data_Subjects_PTSDtypeSHORT2` , `Data_Subjects_Controltype` , `Data_Subjects_Strain_or_Population` , `Data_Subjects_ptsd-measure` , 

#`Data_Subjects_ResSus.split.final` , 

`Data_Method_TimeTask-Trauma` , `task` , `Data_Method_animal light dark testing?` , `measure` , `Comparison` , `ID_Experimental_group` , `ID_Control_group` , `Data_Outcome1_VarName` , `Data_Outcome1_M` , `Data_Outcome1_SD` , `Data_Outcome1_SEM` , `Data_Outcome2_VarName` , `Data_Outcome2_M` , `Data_Outcome2_SD` , `Data_Outcome2_SEM` )


df3h %>% rename(
  author =  `First Author` , 
  year = `Publication Year` , 
  PMID = `PMID` , 
  decision = `inclusion.final` , 
  subject = `subject` , 
  nPTSD = `Data_Subjects_n_ptsd` , 
  nHC =`Data_Subjects_n_control` , 
  sex.PTSD = `Data_Subjects_gender_ptsd (M = male; F = female; - = not reported)` , 
  sex.HC =`Data_Subjects_gender_control (M = male; F = female; - = not reported)` ,
  age.PTSD.m =`Data_Subjects_m_Age_ptsd (- = not reported)` , 
  age.PTSD.sd =`Data_Subjects_sd_Age_ptsd (- = not reported)` , 
  age.HC.m =`Data_Subjects_m_Age_control (- = not reported)` ,
  age.HC.sd =`Data_Subjects_sd_Age_control (- = not reported)` ,
  
  # only in animal s3
 # shocks.num = `Data_Subjects_FS_#Shocks` , 
 # shocks.amp =`Data_Subjects_FS_Amperage(mA)` , 
 
  ptsd.type = `Data_Subjects_PTSDtypeSHORT2` , 
  control.type = `Data_Subjects_Controltype` , 
  population = `Data_Subjects_Strain_or_Population` , 
  
  # only in human s3
   ptsd.measure = `Data_Subjects_ptsd-measure` , 
  
  # not in s1 or human s2
  # res.sus.split = `Data_Subjects_ResSus.split.final`,
  
  time = `Data_Method_TimeTask-Trauma` , 
  task = `task` , 
  rhythm  =`Data_Method_animal light dark testing?` , 
  measure = `measure` , 
  comparison = `Comparison` , 
  idPTSD =`ID_Experimental_group` , 
  idHC = `ID_Control_group` , 
  outcomePTSD = `Data_Outcome1_VarName` , 
  meanPTSD = `Data_Outcome1_M` , 
  sdPTSD = `Data_Outcome1_SD` , 
  semPTSD = `Data_Outcome1_SEM` , 
  outcomeHC = `Data_Outcome2_VarName` , 
  meanHC =`Data_Outcome2_M` , 
  sdHC = `Data_Outcome2_SD` , 
  semHC = `Data_Outcome2_SEM` 
) -> df3h.renamed
```

# Add missing colnames

```{r}

```


```{r}

str(df1.renamed)
str(df2a.renamed)

merge(df1.renamed, df2a.renamed) %>% View()

full_join(df1.renamed, df2a.renamed)

full_join(df2a.renamed, df3a.renamed)

```

