---
title: "meta-CART TRACE"
author: "Milou Sep"
date: "4/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls()) #clean environment

library(dplyr) #general
library(metacart)
```


```{r data, include=FALSE}
data<-readRDS("processed_data/TRACEprepared.RData")

data %>% select(subject, nPTSD, nHC,
                sex.PTSD, sex.HC, 
                
                control.type, 
                
                ptsd.type2, 
                population2,
                measure2, 
                
                time.pseudo,
                
                rhythm,
                comparison,
                idPTSD, idHC,
                
                age.PTSD.cat,
                age.HC.cat,
                
                subject.cat,
                
                reference,
                
                type, phase, valence, cuectx, id_combination,
                
                yi, vi, each, Valence_Grouped,
                
                ) %>% droplevels()->data1
```



# tree model
```{r metaCART clinical}
# data1 %>% filter( (comparison == "B") )
 # str(data1)
# glimpse(data1)
# 
 # data1 %>% is.na() %>% any()
# 
# data1 %>% filter(complete.cases(data1)) ->data2

data1 %>% 
  filter(subject.cat == "Human") %>% 
  filter(comparison != "B") %>% 
           droplevels() ->clinical
# str(clinical)

# Inclusion sex.PTSD sufficient?
# clinical %>% filter(clinical$sex.PTSD != clinical$sex.HC) # one paper different HF and M .. indeed one group only male (trauma exposed PTSD), others UNexp HC and ptsd (M &F)

set.seed(38923)
REmrt(yi ~ subject + 
        sex.PTSD + #sex.HC +
        control.type + 
        rhythm +
         ptsd.type2 + 
        population2 +
        
        measure2 + # newest
        
        comparison + 
          
        age.PTSD.cat + 
           #age.HC.cat +
          time.pseudo +
          type + 
        phase + valence + 
         Valence_Grouped +
        cuectx,
      vi = vi, data = clinical, 
      c=0.5,  # als dit 0 is wel moderators.. bij 0.5 geen.. (en bij 1 dan logischer wijs ook niet) -> correctie voor type I error (p<0.05)
      # cp=0.1,
      maxL=15,
      xval=10, # bij c=0.5 en xval= 15 no moderator detected. bij 20 ook niet... bij 10 wel
      lookahead = F  # warning kwam door lookahead true, if T no tree detected
      )->REtree.C
```


```{r }
summary(REtree.C)
```


```{r }
plot(REtree.C)
```


```{r}
jpeg(file="results/metaCART.clinical.jpeg", height = 2000, width = 1500, res=300, pointsize = 12)
plot(REtree.C)
dev.off()
```


```{r metaCART preclinical}
data1 %>% filter(subject.cat == "Animal") %>% droplevels() ->preclinical

set.seed(38923)
REmrt(yi ~ subject + 
        sex.PTSD + #sex.HC +
        control.type + 
        rhythm +
         ptsd.type2 + 
        population2 +
        
        measure2+ # newest
        
        comparison + 
          
        age.PTSD.cat + 
           #age.HC.cat +
          time.pseudo +
          type + 
        phase + valence + 
         Valence_Grouped +
        cuectx,
      vi = vi, data = preclinical, 
      c=0.5,  # als dit 0 is wel moderators.. bij 0.5 geen.. (en bij 1 dan logischer wijs ook niet) -> correctie voor type I error (p<0.05)
      maxL=15,
      xval=10,
      lookahead = F  # warnings due to lookahead true  [In if (class(tempQ) == "list") { ... : the condition has length > 1 and only the first element will be used]
      )->REtree.P
```

NB 14.4.21 identical results for lookahead is T or F


```{r }
summary(REtree.P)
```


```{r }
plot(REtree.P)
```


```{r}
jpeg(file="results/metaCART.preclinical.lookahead.jpeg", height = 3000, width = 3000, res=300, pointsize = 12)
plot(REtree.P)
dev.off()
```



```{r}
# new.data<-data.frame( ) # create 1 row with values van de variableen waarvor je wil weten wat het effect is.
# predict(REtree.P)
```


# random forest (= multiple trees)

```{r metaforest}


data %>% select(
  # PMID, 
  # idPTSD, 
                id_combination,
  # subject, 
  subject.cat,
        sex.PTSD , control.type , comparison ,
        age.PTSD.cat , type ,
        phase , valence , 
        # Valence_Grouped +
        cuectx,
  rhythm,
  yi, vi
  
  
  
) %>% 
  droplevels()-> datForest

library(caret)
library(metaforest)

set.seed(94372) #set seeds to a random number
ModelInfo_mf()$notes # method from metaforest

# Set up k-fold grouped CV
fit_control <- trainControl(method = "cv", number = 5, index = groupKFold(datForest$id_combination, k = 5)) # warning with 10-fold crossvalidation "Warning message: In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :There were missing values in resampled performance measures."

# Set up a custom tuning grid for the three tuning parameters of MetaForest
rf_grid <- expand.grid(whichweights = c("random", "fixed", "unif"),
                       mtry = c(2, 4, 6),
                       min.node.size = c(2, 4, 6))


set.seed(94372)
# Train the model
cv.mf.cluster <- train(y = datForest$yi, x = datForest[names(datForest) !="yi"], #from x remove yi
                       study = "id_combination", 
                       method = ModelInfo_mf(), #= method from metaforest. https://rdrr.io/cran/metaforest/man/MetaForest.html
                       trControl = fit_control,
                       tuneGrid = rf_grid,
                        # num.trees = 600, # a bit more than default 500 (for better convergence)
                       data=datForest)

# saveRDS(cv.mf.cluster,file="processed_data/fitted.MetaForest.RDS")


cv.mf.cluster

VarImpPlot(cv.mf.cluster$finalModel)

```

